# Site settings
title: Andrew Reeves
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Reeves
user_description: I'm a Systems Engineer living in Santa Barbara, CA. I believe that technology should enable us to have better lives. I love to break down complex systems to their component parts and rebuild them in ways that make them more efficient and easier to use.
user_title: Systems Engineer
# email: 
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: andrew-reeves-a1a10316b
github_username:  sysadmininator
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
