# Site settings
title: Andrew Reeves
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://sysadmininator.com

# User settings
username: Andrew Reeves
user_description: I'm a Systems Engineer living in Santa Barbara, CA. I believe that technology should enable us to have better lives. I love to break down complex systems to their component parts and rebuild (or explain) them in ways that are more efficient and easier to use.
user_title: Systems Engineer
email: jobops@sysadmininator.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: andrew-reeves-a1a10316b
github_username:  sysadmininator
# medium_username: lorem_ipsum
medium_url: "sysadmininator.com/assets/Andrew Reeves - Resume.pdf"
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
