# Site settings
title: Andrew Reeves
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://sysadmininator.com

# User settings
username: Andrew Reeves
user_description: I'm a Systems Engineer living in Santa Barbara, CA and I believe that technology should enable us to have better lives. I have a proven ability to successfully take on new technologies with industry best practices and transform them into functional and positive user experiences.
user_title: Systems Engineer
email: jobops@sysadmininator.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: sysadmininator
github_username:  sysadmininator
# medium_username: lorem_ipsum
medium_url: "sysadmininator.com/assets/Andrew Reeves - Resume.pdf"
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
